In [54]:
import pandas as pd

In [55]:
import numpy as np

In [56]:
## 일반적으로는 csv, excel, json파일을 불러서 데이터프레임을 만들어주는 편
## 임의로 만들수도 있음.

In [57]:
# json을 사용하는 방법(dic)
df = pd.DataFrame({
    "name": ["홍길동", "박길동"],
    "age": [100, 30],
    "ex": [1, 2]
});

df

  name  age  ex
0  홍길동  100   1
1  박길동   30   2

In [58]:
df['name']

0    홍길동
1    박길동
Name: name, dtype: object

In [59]:
df['age']

0    100
1     30
Name: age, dtype: int64

In [60]:
df['ex']

0    1
1    2
Name: ex, dtype: int64

In [61]:
# desc 테이블명
df.describe() # 데이터프레임 자세하게 보기

              age        ex
count    2.000000  2.000000
mean    65.000000  1.500000
std     49.497475  0.707107
min     30.000000  1.000000
25%     47.500000  1.250000
50%     65.000000  1.500000
75%     82.500000  1.750000
max    100.000000  2.000000

In [62]:
type(df['name'])

pandas.core.series.Series

In [63]:
# 항목에 들어가있는 데이터타입을 한꺼번에 보고 싶은 경우
df.dtypes

name    object
age      int64
ex       int64
dtype: object

In [64]:
df.name #df['name'][] 조건넣어 추출같은 복잡한 추출할 때 선호

0    홍길동
1    박길동
Name: name, dtype: object

In [65]:
df.columns # 항목명만 추출

Index(['name', 'age', 'ex'], dtype='object')

In [66]:
df.values

array([['홍길동', 100, 1],
       ['박길동', 30, 2]], dtype=object)

In [67]:
df[['name', 'age']] 
# df[] 컬럼을 추출할 때 쓰는 대괄호
# df[] 컬럼이 여러개인 경우 ==> 반드시 하나로 묶어주어야 한다. ['name', 'age']
# df[['name', 'age']]

  name  age
0  홍길동  100
1  박길동   30

In [68]:
df['age'][df['age'] > 50]

0    100
Name: age, dtype: int64

In [69]:
# 행 추출 2개를 많이 씀.
# df.loc() --> 현재 인덱스로 잡혀있는 컬럼의 값으로 행 추출
# df.iloc() --> 현재 인덱스로 잡혀있는 컬럼의 인덱스 값으로 행 추출

In [70]:
df

  name  age  ex
0  홍길동  100   1
1  박길동   30   2

In [71]:
# 데이터프레임을 만들때 인덱스를 지정안하면 정수자동증가기능을 이용해서
# 값이 정수값으로 이루어진 정수 인덱스가 생성됨.
# 값 인덱스 [0,1,2,3,4,5] 생성 --> loc()
# 위치 인덱스 [0,1,2,3,4,5] 생성 --> iloc()

# 데이터프레임을 만들때 인덱스를 지정하면 내가 지정한 값으로 인덱스가 생성됨.
# apple, ice가 인덱스를 생성한 경우 문자열로 인덱스가 생성됨.
# 이 때의 경우에는 숫자 인덱스를 쓸 수 있음.
# 값 인덱스 ["apple", "ice"] 생성 --> loc()
# 위치 인덱스 [0,1] 생성 --> iloc()

In [72]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [73]:
df.loc[0] # 0행, 첫 가로줄

name    홍길동
age     100
ex        1
Name: 0, dtype: object

In [74]:
df.loc[1]

name    박길동
age      30
ex        2
Name: 1, dtype: object

In [75]:
df.loc[0:2] # 행 추출은 loc, iloc를 써라!

  name  age  ex
0  홍길동  100   1
1  박길동   30   2

In [76]:
df.loc[1, 'name']

'박길동'

In [77]:
df.loc[1, 'age']

np.int64(30)

In [78]:
df.loc[1, ['name', 'age']]

name    박길동
age      30
Name: 1, dtype: object

In [79]:
df.loc[1, 'name':'ex'] # name~ex까지 다!

name    박길동
age      30
ex        2
Name: 1, dtype: object

In [80]:
df.loc[0:2, 'name':'ex']

  name  age  ex
0  홍길동  100   1
1  박길동   30   2

In [81]:
df['age'] + 1 # 원본이 수정되지 않음 --> 비파괴!

0    101
1     31
Name: age, dtype: int64

In [82]:
df['age'] = df['age'] + 1
df

  name  age  ex
0  홍길동  101   1
1  박길동   31   2

In [83]:
df['age'] = df['age'] - 1
df

  name  age  ex
0  홍길동  100   1
1  박길동   30   2

In [84]:
df['next_age'] = df['age'] + 1 # 새로운 컬럼 추가
df

  name  age  ex  next_age
0  홍길동  100   1       101
1  박길동   30   2        31

In [85]:
df.iloc[0,0] # 0행 0열 (0행의 name)

'홍길동'

In [86]:
df.iloc[0,1] # 0행 1열 (0행의 age)

np.int64(100)

In [87]:
df.iloc[0,2] # 0행 2열 (0행의 ex)

np.int64(1)

In [88]:
df.iloc[0,3] # 0행 3열 (0행의 next_age)

np.int64(101)

In [89]:
df.iloc[0,3] = 200
df

  name  age  ex  next_age
0  홍길동  100   1       200
1  박길동   30   2        31

In [90]:
df.iloc[1,0] = "최길동"
df

  name  age  ex  next_age
0  홍길동  100   1       200
1  최길동   30   2        31

In [91]:
df.set_index('ex', inplace=True)
# 비파괴함수 --> inplace = True(파괴, 원본에 반영됨.)

In [92]:
df

   name  age  next_age
ex
1   홍길동  100       200
2   최길동   30        31