In [64]:
# member, orders, total
# apple   100     1000
# ice     200     2000
# song    300     3000

# 위 데이터를 데이터 프레임(member_df)에 넣고 출력
# 1.member컬럼 추출후 출력
# 2.member, orders컬럼 추출후 출력
# 3.첫번째 행 추출후 출력
# 4.세번째 행 추출후 출력
# 5.첫번째부터 두번째 행 추출후 출력
# 6.orders컬럼을 추출(orders값이 150이상인 조건)
# 7.total컬럼에 모두 100을 더해 df에 반영, member_df출력
# 8.orders과 total컬럼의 값을 곱해서 result 컬럼에 넣은 후 출력
# 9.song의 값을 winner로 변경후 출력
# 10.인덱스를 member로 변경후 winner라는 인덱스값으로 행 추출 후 출력

In [65]:
import pandas as pd

In [66]:
member_df = pd.DataFrame({
    'member': ['apple', 'ice', 'song'],
    'orders': [100, 200, 300],
    'total': [1000, 2000, 3000]
})

member_df

  member  orders  total
0  apple     100   1000
1    ice     200   2000
2   song     300   3000

In [67]:
member_df['member']

0    apple
1      ice
2     song
Name: member, dtype: object

In [68]:
member_df[['member', 'orders']]

  member  orders
0  apple     100
1    ice     200
2   song     300

In [69]:
member_df.loc[0]

member    apple
orders      100
total      1000
Name: 0, dtype: object

In [70]:
member_df.loc[2]

member    song
orders     300
total     3000
Name: 2, dtype: object

In [71]:
member_df.loc[0:1]

  member  orders  total
0  apple     100   1000
1    ice     200   2000

In [72]:
member_df['orders'][member_df['orders'] >= 150]

1    200
2    300
Name: orders, dtype: int64

In [73]:
member_df['total'] = member_df['total'] + 100
member_df

  member  orders  total
0  apple     100   1100
1    ice     200   2100
2   song     300   3100

In [74]:
member_df['result'] = member_df['orders'] * member_df['total']
member_df

  member  orders  total  result
0  apple     100   1100  110000
1    ice     200   2100  420000
2   song     300   3100  930000

In [75]:
member_df.iloc[2,0] = 'winner'
member_df

   member  orders  total  result
0   apple     100   1100  110000
1     ice     200   2100  420000
2  winner     300   3100  930000

In [76]:
member_df.set_index('member', inplace=True)

In [78]:
member_df

        orders  total  result
member
apple      100   1100  110000
ice        200   2100  420000
winner     300   3100  930000

In [79]:
member_df.loc['winner']

orders       300
total       3100
result    930000
Name: winner, dtype: int64