In [442]:
# 테이블 형태(df)로 읽어오기 위한 라이브러리 필요
# 데이터를 탐색할 때 그래프를 사용하고 싶은 경우 그래프 라이브러리 필요

In [443]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [444]:
df = pd.read_csv("scientists.csv", encoding = "UTF-8");
df

# def read_csv("scientists.csv", encoding="utf8"):
#     return DataFrame(file, encoding);

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [445]:
df.columns

Index(['Name', 'Born', 'Died', 'Age', 'Occupation'], dtype='object')

In [446]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [447]:
df.dtypes

Name          object
Born          object
Died          object
Age            int64
Occupation    object
dtype: object

In [448]:
df.shape # 테이블의 행과 열의 개수

(8, 5)

In [449]:
df.info() # 컬럼명 + dtypes(각 컬럼별 데이터타입) + null이 있는지까지 + 용량 + row수

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Born        8 non-null      object
 2   Died        8 non-null      object
 3   Age         8 non-null      int64
 4   Occupation  8 non-null      object
dtypes: int64(1), object(4)
memory usage: 452.0+ bytes

In [450]:
df.head() # 위에서부터 5개의 row를 추출

                   Name        Born        Died  Age    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1        William Gosset  1876-06-13  1937-10-16   61  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90         Nurse
3           Marie Curie  1867-11-07  1934-07-04   66       Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56     Biologist

In [451]:
df.head(2)

                Name        Born        Died  Age    Occupation
0  Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1     William Gosset  1876-06-13  1937-10-16   61  Statistician

In [452]:
df.tail() # 맨 끝에서부터 5개의 row를 추출

            Name        Born        Died  Age          Occupation
3    Marie Curie  1867-11-07  1934-07-04   66             Chemist
4  Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5      John Snow  1813-03-15  1858-06-16   45           Physician
6    Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7   Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [453]:
df.tail(3)

           Name        Born        Died  Age          Occupation
5     John Snow  1813-03-15  1858-06-16   45           Physician
6   Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7  Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [454]:
df.describe() # 값의 분포를 확인하기 위함, 수치만 보임.

             Age
count   8.000000
mean   59.125000
std    18.325918
min    37.000000
25%    44.000000
50%    58.500000
75%    68.750000
max    90.000000

In [455]:
df.describe(include='object')

                     Name        Born        Died Occupation
count                   8           8           8          8
unique                  8           8           8          7
top     Rosaline Franklin  1920-07-25  1958-04-16    Chemist
freq                    1           1           1          2

In [456]:
df.count() # null빼고 각 항목(feature)의 개수

Name          8
Born          8
Died          8
Age           8
Occupation    8
dtype: int64

In [457]:
# 값별로 빈도수
df['Occupation'].value_counts()

Occupation
Chemist               2
Statistician          1
Nurse                 1
Biologist             1
Physician             1
Computer Scientist    1
Mathematician         1
Name: count, dtype: int64

In [458]:
df['Age'].value_counts()

Age
37    1
61    1
90    1
66    1
56    1
45    1
41    1
77    1
Name: count, dtype: int64

In [459]:
df.T # 비파괴

,0,1,2,3,4,5,6,7
Name,Rosaline Franklin,William Gosset,Florence Nightingale,Marie Curie,Rachel Carson,John Snow,Alan Turing,Johann Gauss
Born,1920-07-25,1876-06-13,1820-05-12,1867-11-07,1907-05-27,1813-03-15,1912-06-23,1777-04-30
Died,1958-04-16,1937-10-16,1910-08-13,1934-07-04,1964-04-14,1858-06-16,1954-06-07,1855-02-23
Age,37,61,90,66,56,45,41,77
Occupation,Chemist,Statistician,Nurse,Chemist,Biologist,Physician,Computer Scientist,Mathematician

In [460]:
df.sort_index() # 오름차순

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [461]:
df.sort_index(ascending=False) # 내림차순

                   Name        Born        Died  Age          Occupation
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
5             John Snow  1813-03-15  1858-06-16   45           Physician
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist

In [462]:
df.sort_values(by = 'Age') # 인덱스 말고 다른 항목으로 정렬하고 싶을때

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
5             John Snow  1813-03-15  1858-06-16   45           Physician
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse

In [463]:
df.sort_values(['Occupation', 'Age'])

                   Name        Born        Died  Age          Occupation
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
5             John Snow  1813-03-15  1858-06-16   45           Physician
1        William Gosset  1876-06-13  1937-10-16   61        Statistician

In [464]:
df.sort_values(['Occupation', 'Age'], ascending=[True, False])

                   Name        Born        Died  Age          Occupation
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
5             John Snow  1813-03-15  1858-06-16   45           Physician
1        William Gosset  1876-06-13  1937-10-16   61        Statistician

In [465]:
df.sort_values(['Occupation', 'Age'], ascending=[True, False])['Age']

4    56
3    66
0    37
6    41
7    77
2    90
5    45
1    61
Name: Age, dtype: int64

In [466]:
df.sort_values(['Occupation', 'Age'], ascending=[True, False])[['Occupation', 'Age']]

           Occupation  Age
4           Biologist   56
3             Chemist   66
0             Chemist   37
6  Computer Scientist   41
7       Mathematician   77
2               Nurse   90
5           Physician   45
1        Statistician   61

In [467]:
# 조건을 주고 탐색 후 값을 수정

In [468]:
# df[조건]
df[df['Age'] > 61]

                   Name        Born        Died  Age     Occupation
2  Florence Nightingale  1820-05-12  1910-08-13   90          Nurse
3           Marie Curie  1867-11-07  1934-07-04   66        Chemist
7          Johann Gauss  1777-04-30  1855-02-23   77  Mathematician

In [469]:
# df[조건][조건 검색한 후 보고싶은 컬럼]
# 컬럼쓸때 하나일 때는 그냥 컬럼명, 여러개일 때는 무조건 리스트로 묶어줘라.!
df[df['Age'] > 61]['Age']

2    90
3    66
7    77
Name: Age, dtype: int64

In [470]:
df[df['Age'] > 61][['Age', 'Name']]

   Age                  Name
2   90  Florence Nightingale
3   66           Marie Curie
7   77          Johann Gauss

In [471]:
result= df[df['Age'] > 61][['Age', 'Name']]
type(result)

pandas.core.frame.DataFrame

In [472]:
# 조건 검색한 결과 테이블은 데이터 타입은 df임
# df에서 할 수 있는 타입보고, 카운트해보는 등의 작업을 더 해볼 수 있음.!

In [473]:
import seaborn as sns

In [474]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [475]:
sns.load_dataset('iris') # seaborn 설치시 csv여러개를 다운로드 받음.
                         # 이름을 가지고 csv를 읽어올 수 있음.

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [476]:
sns.load_dataset('titanic')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [477]:
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [478]:
sns.load_dataset('mpg')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [479]:
iris = sns.load_dataset('iris')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [480]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [481]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [482]:
iris.describe(include='object')

       species
count      150
unique       3
top     setosa
freq        50

In [483]:
titanic = sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [484]:
titanic.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [485]:
titanic['survived'].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [486]:
titanic['alive'].value_counts()

alive
no     549
yes    342
Name: count, dtype: int64

In [487]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [488]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [489]:
titanic.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [490]:
# result1 = titanic[조건][컬럼명][행범위]
result1 = titanic[titanic['age'] < 1]
result1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False

In [491]:
result2 = titanic[titanic['age'] < 1]['survived']
result2

78     1
305    1
469    1
644    1
755    1
803    1
831    1
Name: survived, dtype: int64

In [492]:
titanic[titanic['age'] < 1]['survived'].count()

np.int64(7)

In [493]:
titanic[titanic['age'] < 1][['age', 'survived']]

      age  survived
78   0.83         1
305  0.92         1
469  0.75         1
644  0.75         1
755  0.67         1
803  0.42         1
831  0.83         1

In [494]:
titanic[titanic['age'] < 1][['age', 'survived']][:3]

      age  survived
78   0.83         1
305  0.92         1
469  0.75         1

In [495]:
titanic[titanic['age'] < 1][['age', 'survived']][-3:-1] # -3~-2

      age  survived
755  0.67         1
803  0.42         1

In [496]:
titanic[titanic['age'] < 1][['age', 'survived']].tail(2)

      age  survived
803  0.42         1
831  0.83         1

In [497]:
titanic.sort_values(by = 'fare').head(1) # 제일 적게 낸 사람

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
815,0,1,male,NaN,0,0,0.0,S,First,man,True,B,Southampton,no,True

In [498]:
titanic.sort_values(by = 'fare').tail(1) # 제일 많이 낸 사람

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True

In [499]:
titanic[(titanic['age'] > 20) & (titanic['age'] < 30)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
34,0,1,male,28.0,1,0,82.1708,C,First,man,True,NaN,Cherbourg,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [500]:
titanic[(titanic['age'] > 20) & (titanic['age'] < 30)]['age'].count()

np.int64(205)

In [501]:
titanic[titanic['pclass'].isin([1, 2])][['pclass', 'age']]

     pclass   age
1         1  38.0
3         1  35.0
6         1  54.0
9         2  14.0
11        1  58.0
..      ...   ...
880       2  25.0
883       2  28.0
886       2  27.0
887       1  19.0
889       1  26.0

[400 rows x 2 columns]

In [502]:
titanic[titanic['pclass'].isin([1, 2])]['age'].mean()

np.float64(34.206824512534816)

In [503]:
titanic[titanic['pclass'].isin([3])]['age'].mean()

np.float64(25.14061971830986)

In [504]:
titanic['deck'] = False 
# 모든 행의 값이 다 False로 들어감.
# 있는 컬럼 이름을 쓰면 다 덮어씀.
# 전체 행에 미치는 연산 --> broadcast, broadcasting

In [505]:
titanic['deck'].head()

0    False
1    False
2    False
3    False
4    False
Name: deck, dtype: bool

In [506]:
# 없는 컬럼 이름을 쓰면 추가가 됨.
titanic['vip'] = False

In [507]:
titanic['vip']

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: vip, Length: 891, dtype: bool

In [508]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,vip
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,False,Southampton,no,False,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,False,Cherbourg,yes,False,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,False,Southampton,yes,True,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,False,Southampton,yes,False,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,False,Southampton,no,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,False,Southampton,no,True,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,False,Southampton,yes,True,False
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,False,Southampton,no,False,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,False,Cherbourg,yes,True,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,False,Queenstown,no,True,False

In [509]:
# class컬럼의 값에 모두 뒤에 "등급"이라고 붙여서 수정(덮어쓰기)
titanic['class'] = titanic['class'].astype(str) + "등급"
titanic['class']

# titanic['class'] = str(titanic['class']) + '등급'
# str(단일값)만 가능!!

0       Third등급
1       First등급
2       Third등급
3       First등급
4       Third등급
         ...
886    Second등급
887     First등급
888     Third등급
889     First등급
890     Third등급
Name: class, Length: 891, dtype: object

In [514]:
titanic['class'].dtype

dtype('O')

In [513]:
# class컬럼의 값에 모두 앞에 "수정된"이라고 붙여서 new_class컬럼에 넣어 컬럼 추가
# 수정과 컬럼추가 출력해보세요.
titanic['new_class'] = "수정된 " + titanic['class']
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,vip,new_class,new_pclass
0,0,3,male,22.0,1,0,7.2500,S,Third등급,man,True,False,Southampton,no,False,False,수정된 Third등급,203
1,1,1,female,38.0,1,0,71.2833,C,First등급,woman,False,False,Cherbourg,yes,False,False,수정된 First등급,201
2,1,3,female,26.0,0,0,7.9250,S,Third등급,woman,False,False,Southampton,yes,True,False,수정된 Third등급,203
3,1,1,female,35.0,1,0,53.1000,S,First등급,woman,False,False,Southampton,yes,False,False,수정된 First등급,201
4,0,3,male,35.0,0,0,8.0500,S,Third등급,man,True,False,Southampton,no,True,False,수정된 Third등급,203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second등급,man,True,False,Southampton,no,True,False,수정된 Second등급,202
887,1,1,female,19.0,0,0,30.0000,S,First등급,woman,False,False,Southampton,yes,True,False,수정된 First등급,201
888,0,3,female,NaN,1,2,23.4500,S,Third등급,woman,False,False,Southampton,no,False,False,수정된 Third등급,203
889,1,1,male,26.0,0,0,30.0000,C,First등급,man,True,False,Cherbourg,yes,True,False,수정된 First등급,201
890,0,3,male,32.0,0,0,7.7500,Q,Third등급,man,True,False,Queenstown,no,True,False,수정된 Third등급,203

In [511]:
titanic['pclass'].dtypes

dtype('int64')

In [512]:
titanic['new_pclass'] = titanic['pclass'] + 200
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,vip,new_class,new_pclass
0,0,3,male,22.0,1,0,7.2500,S,Third등급,man,True,False,Southampton,no,False,False,수정된 Third등급,203
1,1,1,female,38.0,1,0,71.2833,C,First등급,woman,False,False,Cherbourg,yes,False,False,수정된 First등급,201
2,1,3,female,26.0,0,0,7.9250,S,Third등급,woman,False,False,Southampton,yes,True,False,수정된 Third등급,203
3,1,1,female,35.0,1,0,53.1000,S,First등급,woman,False,False,Southampton,yes,False,False,수정된 First등급,201
4,0,3,male,35.0,0,0,8.0500,S,Third등급,man,True,False,Southampton,no,True,False,수정된 Third등급,203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second등급,man,True,False,Southampton,no,True,False,수정된 Second등급,202
887,1,1,female,19.0,0,0,30.0000,S,First등급,woman,False,False,Southampton,yes,True,False,수정된 First등급,201
888,0,3,female,NaN,1,2,23.4500,S,Third등급,woman,False,False,Southampton,no,False,False,수정된 Third등급,203
889,1,1,male,26.0,0,0,30.0000,C,First등급,man,True,False,Cherbourg,yes,True,False,수정된 First등급,201
890,0,3,male,32.0,0,0,7.7500,Q,Third등급,man,True,False,Queenstown,no,True,False,수정된 Third등급,203

In [519]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'vip', 'new_class', 'new_pclass'],
      dtype='object')

In [521]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,vip,new_class,new_pclass
0,0,3,male,22.0,1,0,7.2500,S,Third등급,man,True,False,Southampton,no,False,False,수정된 Third등급,203
1,1,1,female,38.0,1,0,71.2833,C,First등급,woman,False,False,Cherbourg,yes,False,False,수정된 First등급,201
2,1,3,female,26.0,0,0,7.9250,S,Third등급,woman,False,False,Southampton,yes,True,False,수정된 Third등급,203
3,1,1,female,35.0,1,0,53.1000,S,First등급,woman,False,False,Southampton,yes,False,False,수정된 First등급,201
4,0,3,male,35.0,0,0,8.0500,S,Third등급,man,True,False,Southampton,no,True,False,수정된 Third등급,203

In [522]:
titanic.drop(0)
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,vip,new_class,new_pclass
0,0,3,male,22.0,1,0,7.2500,S,Third등급,man,True,False,Southampton,no,False,False,수정된 Third등급,203
1,1,1,female,38.0,1,0,71.2833,C,First등급,woman,False,False,Cherbourg,yes,False,False,수정된 First등급,201
2,1,3,female,26.0,0,0,7.9250,S,Third등급,woman,False,False,Southampton,yes,True,False,수정된 Third등급,203
3,1,1,female,35.0,1,0,53.1000,S,First등급,woman,False,False,Southampton,yes,False,False,수정된 First등급,201
4,0,3,male,35.0,0,0,8.0500,S,Third등급,man,True,False,Southampton,no,True,False,수정된 Third등급,203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second등급,man,True,False,Southampton,no,True,False,수정된 Second등급,202
887,1,1,female,19.0,0,0,30.0000,S,First등급,woman,False,False,Southampton,yes,True,False,수정된 First등급,201
888,0,3,female,NaN,1,2,23.4500,S,Third등급,woman,False,False,Southampton,no,False,False,수정된 Third등급,203
889,1,1,male,26.0,0,0,30.0000,C,First등급,man,True,False,Cherbourg,yes,True,False,수정된 First등급,201
890,0,3,male,32.0,0,0,7.7500,Q,Third등급,man,True,False,Queenstown,no,True,False,수정된 Third등급,203

In [523]:
titanic.drop(0, inplace=True)

In [524]:
titanic.count()

survived       890
pclass         890
sex            890
age            713
sibsp          890
parch          890
fare           890
embarked       888
class          890
who            890
adult_male     890
deck           890
embark_town    888
alive          890
alone          890
vip            890
new_class      890
new_pclass     890
dtype: int64

In [525]:
titanic.drop(10, inplace=True)

In [526]:
titanic.count()

survived       889
pclass         889
sex            889
age            712
sibsp          889
parch          889
fare           889
embarked       887
class          889
who            889
adult_male     889
deck           889
embark_town    887
alive          889
alone          889
vip            889
new_class      889
new_pclass     889
dtype: int64

In [527]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,vip,new_class,new_pclass
1,1,1,female,38.0,1,0,71.2833,C,First등급,woman,False,False,Cherbourg,yes,False,False,수정된 First등급,201
2,1,3,female,26.0,0,0,7.9250,S,Third등급,woman,False,False,Southampton,yes,True,False,수정된 Third등급,203
3,1,1,female,35.0,1,0,53.1000,S,First등급,woman,False,False,Southampton,yes,False,False,수정된 First등급,201
4,0,3,male,35.0,0,0,8.0500,S,Third등급,man,True,False,Southampton,no,True,False,수정된 Third등급,203
5,0,3,male,NaN,0,0,8.4583,Q,Third등급,man,True,False,Queenstown,no,True,False,수정된 Third등급,203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second등급,man,True,False,Southampton,no,True,False,수정된 Second등급,202
887,1,1,female,19.0,0,0,30.0000,S,First등급,woman,False,False,Southampton,yes,True,False,수정된 First등급,201
888,0,3,female,NaN,1,2,23.4500,S,Third등급,woman,False,False,Southampton,no,False,False,수정된 Third등급,203
889,1,1,male,26.0,0,0,30.0000,C,First등급,man,True,False,Cherbourg,yes,True,False,수정된 First등급,201
890,0,3,male,32.0,0,0,7.7500,Q,Third등급,man,True,False,Queenstown,no,True,False,수정된 Third등급,203

In [528]:
titanic.drop(1, inplace=True)

In [529]:
titanic.count()

survived       888
pclass         888
sex            888
age            711
sibsp          888
parch          888
fare           888
embarked       886
class          888
who            888
adult_male     888
deck           888
embark_town    886
alive          888
alone          888
vip            888
new_class      888
new_pclass     888
dtype: int64

In [530]:
titanic.drop(890) # 비파괴

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,vip,new_class,new_pclass
2,1,3,female,26.0,0,0,7.9250,S,Third등급,woman,False,False,Southampton,yes,True,False,수정된 Third등급,203
3,1,1,female,35.0,1,0,53.1000,S,First등급,woman,False,False,Southampton,yes,False,False,수정된 First등급,201
4,0,3,male,35.0,0,0,8.0500,S,Third등급,man,True,False,Southampton,no,True,False,수정된 Third등급,203
5,0,3,male,NaN,0,0,8.4583,Q,Third등급,man,True,False,Queenstown,no,True,False,수정된 Third등급,203
6,0,1,male,54.0,0,0,51.8625,S,First등급,man,True,False,Southampton,no,True,False,수정된 First등급,201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third등급,woman,False,False,Queenstown,no,False,False,수정된 Third등급,203
886,0,2,male,27.0,0,0,13.0000,S,Second등급,man,True,False,Southampton,no,True,False,수정된 Second등급,202
887,1,1,female,19.0,0,0,30.0000,S,First등급,woman,False,False,Southampton,yes,True,False,수정된 First등급,201
888,0,3,female,NaN,1,2,23.4500,S,Third등급,woman,False,False,Southampton,no,False,False,수정된 Third등급,203
889,1,1,male,26.0,0,0,30.0000,C,First등급,man,True,False,Cherbourg,yes,True,False,수정된 First등급,201

In [531]:
titanic.count()

survived       888
pclass         888
sex            888
age            711
sibsp          888
parch          888
fare           888
embarked       886
class          888
who            888
adult_male     888
deck           888
embark_town    886
alive          888
alone          888
vip            888
new_class      888
new_pclass     888
dtype: int64

In [532]:
titanic.drop(890, inplace=True) # 비파괴

In [533]:
titanic.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,vip,new_class,new_pclass
885,0,3,female,39.0,0,5,29.125,Q,Third등급,woman,False,False,Queenstown,no,False,False,수정된 Third등급,203
886,0,2,male,27.0,0,0,13.000,S,Second등급,man,True,False,Southampton,no,True,False,수정된 Second등급,202
887,1,1,female,19.0,0,0,30.000,S,First등급,woman,False,False,Southampton,yes,True,False,수정된 First등급,201
888,0,3,female,NaN,1,2,23.450,S,Third등급,woman,False,False,Southampton,no,False,False,수정된 Third등급,203
889,1,1,male,26.0,0,0,30.000,C,First등급,man,True,False,Cherbourg,yes,True,False,수정된 First등급,201

In [534]:
titanic.drop(888, inplace=True)

In [535]:
titanic.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,vip,new_class,new_pclass
884,0,3,male,25.0,0,0,7.050,S,Third등급,man,True,False,Southampton,no,True,False,수정된 Third등급,203
885,0,3,female,39.0,0,5,29.125,Q,Third등급,woman,False,False,Queenstown,no,False,False,수정된 Third등급,203
886,0,2,male,27.0,0,0,13.000,S,Second등급,man,True,False,Southampton,no,True,False,수정된 Second등급,202
887,1,1,female,19.0,0,0,30.000,S,First등급,woman,False,False,Southampton,yes,True,False,수정된 First등급,201
889,1,1,male,26.0,0,0,30.000,C,First등급,man,True,False,Cherbourg,yes,True,False,수정된 First등급,201

In [537]:
titanic.drop(titanic.index[0 : 3], inplace = True)

In [538]:
titanic.count()

survived       883
pclass         883
sex            883
age            707
sibsp          883
parch          883
fare           883
embarked       881
class          883
who            883
adult_male     883
deck           883
embark_town    881
alive          883
alone          883
vip            883
new_class      883
new_pclass     883
dtype: int64

In [540]:
titanic.drop(titanic.index[[882, 880]], inplace = True) ### index로 삭제

In [541]:
titanic.count()

survived       881
pclass         881
sex            881
age            705
sibsp          881
parch          881
fare           881
embarked       879
class          881
who            881
adult_male     881
deck           881
embark_town    879
alive          881
alone          881
vip            881
new_class      881
new_pclass     881
dtype: int64

In [543]:
# titanic.drop(행 인덱스 값), titanic.drop(titanic.index[행 인덱스 번호] : 행삭제
# titanic.drop(열이름, axis = 1) : 열삭제

In [544]:
titanic.drop('new_pclass', axis = 1, inplace = True)

In [545]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'vip', 'new_class'],
      dtype='object')

In [546]:
titanic.drop('vip', axis = 1, inplace = True)

In [547]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'new_class'],
      dtype='object')

In [548]:
titanic.drop(['adult_male', 'embark_town', 'embarked'], axis = 1, inplace = True)

In [549]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'class',
       'who', 'deck', 'alive', 'alone', 'new_class'],
      dtype='object')

In [550]:
titanic2 = titanic.copy() # 깊은 복사
titanic2.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'class',
       'who', 'deck', 'alive', 'alone', 'new_class'],
      dtype='object')