In [53]:
# 0. scientist.csv
# 1. df로 읽어들이고
# 2. df의 전체 데이터셋 타입을 확인
# 3. df의 컬럼리스트를 확인
# 4. df의 값을 확인
# 5. df의 맨 마지막에 price항목을 추가(값은 임의대로 넣음. int)
# 6. df의 맨 마지막에 percent항목을 추가(값의 임의대로 넣음. float)
# 7. df의 맨 마지막에 sale항목을 추가(price * percent)
# 8. df의 Name컬럼 추출
# 9. df의 인덱스 확인
# 10. df의 Name컬럼의 값이 Rosaline인 행 추출
# 11. df의 Name컬럼 중 3~5사이의 행 추출
# 12. df의 Name, Died컬럼 모든 행 추출
# 13. df의 Born컬럼부터 끝컬럼까지 모든 행 추출
# 14. df의 Born, Age컬럼의 5~7행 추출
# 15. df.shape을 통해 몇행 몇열인지 확인해보세요.
# 16. df의 숫자 데이터의 상세정보 확인
# 17. Nurse라는 스트링 추출(index와 컬럼명을 사용)
# 18. Alan Turing이라는 스트링 추출(index와 컬럼명을 사용)
# 19. Biologist를 Scientist로 변경
# 20. df의 변경된 내용은 수시로 프린트해볼 것.

In [54]:
import pandas as pd ## df
import matplotlib.pyplot as plt ## 시각화
import numpy as np ## 수학적인 처리 함수
import seaborn as sns ## 다양한 데이터셋과 시각화 함수

In [55]:
# 1. df로 읽어들이고
df = pd.read_csv("scientists.csv", encoding="UTF-8")
df

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [56]:
# 2. df의 전체 데이터셋 타입을 확인
df.dtypes

Name          object
Born          object
Died          object
Age            int64
Occupation    object
dtype: object

In [57]:
# 3. df의 컬럼리스트를 확인
df.columns

Index(['Name', 'Born', 'Died', 'Age', 'Occupation'], dtype='object')

In [58]:
# 4. df의 값을 확인
df.values

array([['Rosaline Franklin', '1920-07-25', '1958-04-16', 37, 'Chemist'],
       ['William Gosset', '1876-06-13', '1937-10-16', 61, 'Statistician'],
       ['Florence Nightingale', '1820-05-12', '1910-08-13', 90, 'Nurse'],
       ['Marie Curie', '1867-11-07', '1934-07-04', 66, 'Chemist'],
       ['Rachel Carson', '1907-05-27', '1964-04-14', 56, 'Biologist'],
       ['John Snow', '1813-03-15', '1858-06-16', 45, 'Physician'],
       ['Alan Turing', '1912-06-23', '1954-06-07', 41,
        'Computer Scientist'],
       ['Johann Gauss', '1777-04-30', '1855-02-23', 77, 'Mathematician']],
      dtype=object)

In [59]:
# 5. df의 맨 마지막에 price항목을 추가(값은 임의대로 넣음. int)
# df['price'] = 10
# df['price'] = range(1, 9) # row 개수와 일치해야함. range(1, 9) ==> [1,2,3,4,5,6,7,8]
df['price'] = np.random.randint(1,100, size=len(df))
df

,Name,Born,Died,Age,Occupation,price
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,10
1,William Gosset,1876-06-13,1937-10-16,61,Statistician,96
2,Florence Nightingale,1820-05-12,1910-08-13,90,Nurse,94
3,Marie Curie,1867-11-07,1934-07-04,66,Chemist,14
4,Rachel Carson,1907-05-27,1964-04-14,56,Biologist,10
5,John Snow,1813-03-15,1858-06-16,45,Physician,28
6,Alan Turing,1912-06-23,1954-06-07,41,Computer Scientist,40
7,Johann Gauss,1777-04-30,1855-02-23,77,Mathematician,10

In [60]:
# 6. df의 맨 마지막에 percent항목을 추가(값의 임의대로 넣음. float)
# df['percent'] = 0.5
df['percent'] = np.random.uniform(1,100, size=len(df))
df['percent'] = df['percent'].round(1)
df

,Name,Born,Died,Age,Occupation,price,percent
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,10,13.0
1,William Gosset,1876-06-13,1937-10-16,61,Statistician,96,54.3
2,Florence Nightingale,1820-05-12,1910-08-13,90,Nurse,94,69.7
3,Marie Curie,1867-11-07,1934-07-04,66,Chemist,14,71.9
4,Rachel Carson,1907-05-27,1964-04-14,56,Biologist,10,8.9
5,John Snow,1813-03-15,1858-06-16,45,Physician,28,52.0
6,Alan Turing,1912-06-23,1954-06-07,41,Computer Scientist,40,50.4
7,Johann Gauss,1777-04-30,1855-02-23,77,Mathematician,10,67.4

In [61]:
# 7. df의 맨 마지막에 sale항목을 추가(price * percent)
df['sale'] = df['price'] * df['percent']
df

,Name,Born,Died,Age,Occupation,price,percent,sale
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,10,13.0,130.0
1,William Gosset,1876-06-13,1937-10-16,61,Statistician,96,54.3,5212.8
2,Florence Nightingale,1820-05-12,1910-08-13,90,Nurse,94,69.7,6551.8
3,Marie Curie,1867-11-07,1934-07-04,66,Chemist,14,71.9,1006.6
4,Rachel Carson,1907-05-27,1964-04-14,56,Biologist,10,8.9,89.0
5,John Snow,1813-03-15,1858-06-16,45,Physician,28,52.0,1456.0
6,Alan Turing,1912-06-23,1954-06-07,41,Computer Scientist,40,50.4,2016.0
7,Johann Gauss,1777-04-30,1855-02-23,77,Mathematician,10,67.4,674.0

In [62]:
df['sale'].dtype

dtype('float64')

In [63]:
# 8. df의 Name컬럼 추출
df['Name']

0       Rosaline Franklin
1          William Gosset
2    Florence Nightingale
3             Marie Curie
4           Rachel Carson
5               John Snow
6             Alan Turing
7            Johann Gauss
Name: Name, dtype: object

In [64]:
# 9. df의 인덱스 확인
df.index

RangeIndex(start=0, stop=8, step=1)

In [65]:
list(df.index)

[0, 1, 2, 3, 4, 5, 6, 7]

In [66]:
# 10. df의 Name컬럼의 값이 Rosaline인 행 추출
# df[조건][열][행]
df[df["Name"] == "Rosaline Franklin"]

,Name,Born,Died,Age,Occupation,price,percent,sale
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,10,13.0,130.0

In [67]:
# 11. df의 Name컬럼 중 3~5사이의 행 추출
df['Name'][3:6] # 조건 필요없으면 묶는 대괄호[] 필요 x

3      Marie Curie
4    Rachel Carson
5        John Snow
Name: Name, dtype: object

In [68]:
# 12. df의 Name, Died컬럼 모든 행 추출
df[['Name', 'Died']]

                   Name        Died
0     Rosaline Franklin  1958-04-16
1        William Gosset  1937-10-16
2  Florence Nightingale  1910-08-13
3           Marie Curie  1934-07-04
4         Rachel Carson  1964-04-14
5             John Snow  1858-06-16
6           Alan Turing  1954-06-07
7          Johann Gauss  1855-02-23

In [69]:
# 13. df의 Born컬럼부터 끝컬럼까지 모든 행 추출
# df.loc[행, 열]
df.loc[:, 'Born':]

         Born        Died  Age          Occupation  price  percent    sale
0  1920-07-25  1958-04-16   37             Chemist     10     13.0   130.0
1  1876-06-13  1937-10-16   61        Statistician     96     54.3  5212.8
2  1820-05-12  1910-08-13   90               Nurse     94     69.7  6551.8
3  1867-11-07  1934-07-04   66             Chemist     14     71.9  1006.6
4  1907-05-27  1964-04-14   56           Biologist     10      8.9    89.0
5  1813-03-15  1858-06-16   45           Physician     28     52.0  1456.0
6  1912-06-23  1954-06-07   41  Computer Scientist     40     50.4  2016.0
7  1777-04-30  1855-02-23   77       Mathematician     10     67.4   674.0

In [70]:
# 14. df의 Born, Age컬럼의 5~7행 추출
df[['Born', 'Age']][5:8]

         Born  Age
5  1813-03-15   45
6  1912-06-23   41
7  1777-04-30   77

In [71]:
# 15. df.shape을 통해 몇행 몇열인지 확인해보세요.
df.shape

(8, 8)

In [72]:
# 16. df의 숫자 데이터의 상세정보 확인
df.describe()

             Age      price    percent         sale
count   8.000000   8.000000   8.000000     8.000000
mean   59.125000  37.750000  48.450000  2142.025000
std    18.325918  36.900445  24.588325  2422.210644
min    37.000000  10.000000   8.900000    89.000000
25%    44.000000  10.000000  41.050000   538.000000
50%    58.500000  21.000000  53.150000  1231.300000
75%    68.750000  53.500000  67.975000  2815.200000
max    90.000000  96.000000  71.900000  6551.800000

In [73]:
df

,Name,Born,Died,Age,Occupation,price,percent,sale
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,10,13.0,130.0
1,William Gosset,1876-06-13,1937-10-16,61,Statistician,96,54.3,5212.8
2,Florence Nightingale,1820-05-12,1910-08-13,90,Nurse,94,69.7,6551.8
3,Marie Curie,1867-11-07,1934-07-04,66,Chemist,14,71.9,1006.6
4,Rachel Carson,1907-05-27,1964-04-14,56,Biologist,10,8.9,89.0
5,John Snow,1813-03-15,1858-06-16,45,Physician,28,52.0,1456.0
6,Alan Turing,1912-06-23,1954-06-07,41,Computer Scientist,40,50.4,2016.0
7,Johann Gauss,1777-04-30,1855-02-23,77,Mathematician,10,67.4,674.0

In [84]:
# 17. Nurse라는 스트링 추출(index와 컬럼명을 사용)
# df.loc[2, 'Occupation']
df['Occupation'][2]

2    Nurse
Name: Occupation, dtype: object

In [85]:
df.loc[df.index[df['Occupation'] == 'Nurse'], 'Occupation']

2    Nurse
Name: Occupation, dtype: object

In [82]:
# 18. Alan Turing이라는 스트링 추출(index와 컬럼명을 사용)
# df.loc[6, 'Name']
df['Name'][6]

'Alan Turing'

In [76]:
# 19. Biologist를 Scientist로 변경
df.iloc[4, 4] = 'Scientist'
df

,Name,Born,Died,Age,Occupation,price,percent,sale
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,10,13.0,130.0
1,William Gosset,1876-06-13,1937-10-16,61,Statistician,96,54.3,5212.8
2,Florence Nightingale,1820-05-12,1910-08-13,90,Nurse,94,69.7,6551.8
3,Marie Curie,1867-11-07,1934-07-04,66,Chemist,14,71.9,1006.6
4,Rachel Carson,1907-05-27,1964-04-14,56,Scientist,10,8.9,89.0
5,John Snow,1813-03-15,1858-06-16,45,Physician,28,52.0,1456.0
6,Alan Turing,1912-06-23,1954-06-07,41,Computer Scientist,40,50.4,2016.0
7,Johann Gauss,1777-04-30,1855-02-23,77,Mathematician,10,67.4,674.0

In [90]:
df.loc[df.index[df['Occupation'] == 'Scientist'], 'Occupation'] = 'Biologist'
df

,Name,Born,Died,Age,Occupation,price,percent,sale
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,10,13.0,130.0
1,William Gosset,1876-06-13,1937-10-16,61,Statistician,96,54.3,5212.8
2,Florence Nightingale,1820-05-12,1910-08-13,90,Nurse,94,69.7,6551.8
3,Marie Curie,1867-11-07,1934-07-04,66,Chemist,14,71.9,1006.6
4,Rachel Carson,1907-05-27,1964-04-14,56,Biologist,10,8.9,89.0
5,John Snow,1813-03-15,1858-06-16,45,Physician,28,52.0,1456.0
6,Alan Turing,1912-06-23,1954-06-07,41,Computer Scientist,40,50.4,2016.0
7,Johann Gauss,1777-04-30,1855-02-23,77,Mathematician,10,67.4,674.0