In [1]:
import pandas as pd
import numpy as np

In [2]:
cctv_seoul = pd.read_csv('../csv-data/cctv_seoul.csv', encoding='utf-8')
cctv_seoul.head()

   기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613

In [3]:
cctv_seoul.columns

Index(['기관명', '소계', '2013년도 이전', '2014년', '2015년', '2016년'], dtype='object')

In [4]:
cctv_seoul[cctv_seoul['기관명'] == '금천구']

   기관명    소계  2013년도 이전  2014년  2015년  2016년
7  금천구  1015        674     51    269    354

In [5]:
cctv_seoul[cctv_seoul['기관명'] == '금천구']['기관명']

7    금천구
Name: 기관명, dtype: object

In [6]:
cctv_seoul['소계'].mean()

np.float64(1179.08)

In [7]:
cctv_seoul.columns

Index(['기관명', '소계', '2013년도 이전', '2014년', '2015년', '2016년'], dtype='object')

In [8]:
# cctv_seoul.columns = [] 전체 컬럼 변경
cctv_seoul.rename(columns={cctv_seoul.columns[0] : "구별"}, inplace=True)

In [9]:
cctv_seoul.columns

Index(['구별', '소계', '2013년도 이전', '2014년', '2015년', '2016년'], dtype='object')

In [10]:
cctv_seoul['소계'].max()

2780

In [11]:
cctv_seoul['소계'].idxmax()

0

In [12]:
cctv_seoul.iloc[0] # loc(값), iloc(위치 인덱스)

구별            강남구
소계           2780
2013년도 이전    1292
2014년         430
2015년         584
2016년         932
Name: 0, dtype: object

In [13]:
cctv_seoul['소계'].idxmin()

9

In [14]:
cctv_seoul.iloc[9]

구별           도봉구
소계           485
2013년도 이전    238
2014년        159
2015년         42
2016년        386
Name: 9, dtype: object

In [15]:
# !pip install --upgrade xlrd

In [16]:
# !conda install -c conda-forge xlrd

In [17]:
# !pip install pandas

In [18]:
pop_seoul = pd.read_excel('../csv-data/pop_seoul.xls')
pop_seoul.head()

,기간,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
0,기간,자치구,세대,합계,합계,합계,한국인,한국인,한국인,등록외국인,등록외국인,등록외국인,세대당인구,65세이상고령자
1,기간,자치구,세대,계,남자,여자,계,남자,여자,계,남자,여자,세대당인구,65세이상고령자
2,2017.1/4,합계,4202888,10197604,5000005,5197599,9926968,4871560,5055408,270636,128445,142191,2.36,1321458
3,2017.1/4,종로구,72654,162820,79675,83145,153589,75611,77978,9231,4064,5167,2.11,25425
4,2017.1/4,중구,59481,133240,65790,67450,124312,61656,62656,8928,4134,4794,2.09,20764

In [19]:
pop_seoul = pd.read_excel('../csv-data/pop_seoul.xls',
                                             header = 2,
                                             usecols= 'B, D, G, J, N'
                         )
pop_seoul.head()

   자치구           계        계.1       계.2   65세이상고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0
2   중구    133240.0   124312.0    8928.0    20764.0
3  용산구    244203.0   229456.0   14747.0    36231.0
4  성동구    311244.0   303380.0    7864.0    39997.0

In [20]:
cctv_seoul.head()

    구별    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613

In [21]:
cctv_seoul.sort_values(by='소계').head()

     구별   소계  2013년도 이전  2014년  2015년  2016년
9   도봉구  485        238    159     42    386
12  마포구  574        314    118    169    379
17  송파구  618        529     21     68    463
24  중랑구  660        509    121    177    109
23   중구  671        413    190     72    348

In [22]:
cctv_seoul.sort_values(by='소계').tail()

     구별    소계  2013년도 이전  2014년  2015년  2016년
20  용산구  1624       1368    218    112    398
21  은평구  1873       1138    224    278    468
14  서초구  1930       1406    157    336    398
18  양천구  2034       1843    142     30    467
0   강남구  2780       1292    430    584    932

In [23]:
cctv_seoul.sort_values(by='소계', ascending=False).head(3)

     구별    소계  2013년도 이전  2014년  2015년  2016년
0   강남구  2780       1292    430    584    932
18  양천구  2034       1843    142     30    467
14  서초구  1930       1406    157    336    398

In [24]:
pop_seoul.columns = ['구별', '인구수', '한국인', '외국인', '고령자']
pop_seoul.head()

    구별         인구수        한국인       외국인        고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0
2   중구    133240.0   124312.0    8928.0    20764.0
3  용산구    244203.0   229456.0   14747.0    36231.0
4  성동구    311244.0   303380.0    7864.0    39997.0

In [25]:
# pop_seoul.drop(행번호, inplace=True)
# pop_seoul.drop(행번호, axis=1. inplace=True)

In [26]:
pop_seoul.drop([0], inplace=True)

In [27]:
pop_seoul.head()

    구별       인구수       한국인      외국인      고령자
1  종로구  162820.0  153589.0   9231.0  25425.0
2   중구  133240.0  124312.0   8928.0  20764.0
3  용산구  244203.0  229456.0  14747.0  36231.0
4  성동구  311244.0  303380.0   7864.0  39997.0
5  광진구  372164.0  357211.0  14953.0  42214.0

In [28]:
pop_seoul.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 1 to 26
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   구별      25 non-null     object
 1   인구수     25 non-null     float64
 2   한국인     25 non-null     float64
 3   외국인     25 non-null     float64
 4   고령자     25 non-null     float64
dtypes: float64(4), object(1)
memory usage: 1.1+ KB

In [29]:
pop_seoul['구별'].unique()

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구', nan],
      dtype=object)

In [30]:
len(pop_seoul['구별'].unique())

26

In [31]:
pop_seoul.tail(1)

     구별  인구수  한국인  외국인  고령자
26  NaN  NaN  NaN  NaN  NaN

In [32]:
# pop_seoul.iloc[-1]
pop_seoul.iloc[25]

구별     NaN
인구수    NaN
한국인    NaN
외국인    NaN
고령자    NaN
Name: 26, dtype: object

In [33]:
pop_seoul.isnull().sum()

구별     1
인구수    1
한국인    1
외국인    1
고령자    1
dtype: int64

In [34]:
pop_seoul

      구별       인구수       한국인      외국인      고령자
1    종로구  162820.0  153589.0   9231.0  25425.0
2     중구  133240.0  124312.0   8928.0  20764.0
3    용산구  244203.0  229456.0  14747.0  36231.0
4    성동구  311244.0  303380.0   7864.0  39997.0
5    광진구  372164.0  357211.0  14953.0  42214.0
6   동대문구  369496.0  354079.0  15417.0  54173.0
7    중랑구  414503.0  409882.0   4621.0  56774.0
8    성북구  461260.0  449773.0  11487.0  64692.0
9    강북구  330192.0  326686.0   3506.0  54813.0
10   도봉구  348646.0  346629.0   2017.0  51312.0
11   노원구  569384.0  565565.0   3819.0  71941.0
12   은평구  494388.0  489943.0   4445.0  72334.0
13  서대문구  327163.0  314982.0  12181.0  48161.0
14   마포구  389649.0  378566.0  11083.0  48765.0
15   양천구  479978.0  475949.0   4029.0  52975.0
16   강서구  603772.0  597248.0   6524.0  72548.0
17   구로구  447874.0  416487.0  31387.0  56833.0
18   금천구  255082.0  236353.0  18729.0  32970.0
19  영등포구  402985.0  368072.0  34913.0  52413.0
20   동작구  412520.0  400456.0  12064.0  56013.0
21   관악구  525515.0  507203.0  18312.0  68082.0
22   서초구  450310.0  445994.0   4316.0  51733.0
23   강남구  570500.0  565550.0   4950.0  63167.0
24   송파구  667483.0  660584.0   6899.0  72506.0
25   강동구  453233.0  449019.0   4214.0  54622.0
26   NaN       NaN       NaN      NaN      NaN

In [35]:
pop_seoul.drop([26], inplace=True)

In [36]:
pop_seoul.isnull().sum()

구별     0
인구수    0
한국인    0
외국인    0
고령자    0
dtype: int64

In [37]:
# 외국인비율, 고령자비율 파생변수를 2개 만들어주세요.!
pop_seoul['외국인비율'] = pop_seoul['외국인'] / pop_seoul['인구수'] * 100
pop_seoul.head()

    구별       인구수       한국인      외국인      고령자     외국인비율
1  종로구  162820.0  153589.0   9231.0  25425.0  5.669451
2   중구  133240.0  124312.0   8928.0  20764.0  6.700690
3  용산구  244203.0  229456.0  14747.0  36231.0  6.038828
4  성동구  311244.0  303380.0   7864.0  39997.0  2.526635
5  광진구  372164.0  357211.0  14953.0  42214.0  4.017852

In [38]:
pop_seoul['고령자비율'] = pop_seoul['고령자'] / pop_seoul['인구수'] * 100
pop_seoul.head()

    구별       인구수       한국인      외국인      고령자     외국인비율      고령자비율
1  종로구  162820.0  153589.0   9231.0  25425.0  5.669451  15.615404
2   중구  133240.0  124312.0   8928.0  20764.0  6.700690  15.583909
3  용산구  244203.0  229456.0  14747.0  36231.0  6.038828  14.836427
4  성동구  311244.0  303380.0   7864.0  39997.0  2.526635  12.850689
5  광진구  372164.0  357211.0  14953.0  42214.0  4.017852  11.342849

In [39]:
pop_seoul.sort_values(by='인구수', ascending=False).head()

     구별       인구수       한국인      외국인      고령자     외국인비율      고령자비율
24  송파구  667483.0  660584.0   6899.0  72506.0  1.033584  10.862599
16  강서구  603772.0  597248.0   6524.0  72548.0  1.080540  12.015794
23  강남구  570500.0  565550.0   4950.0  63167.0  0.867660  11.072217
11  노원구  569384.0  565565.0   3819.0  71941.0  0.670725  12.634883
21  관악구  525515.0  507203.0  18312.0  68082.0  3.484582  12.955291

In [40]:
pop_seoul.sort_values(by='인구수', ascending=False).tail()

     구별       인구수       한국인      외국인      고령자     외국인비율      고령자비율
4   성동구  311244.0  303380.0   7864.0  39997.0  2.526635  12.850689
18  금천구  255082.0  236353.0  18729.0  32970.0  7.342345  12.925255
3   용산구  244203.0  229456.0  14747.0  36231.0  6.038828  14.836427
1   종로구  162820.0  153589.0   9231.0  25425.0  5.669451  15.615404
2    중구  133240.0  124312.0   8928.0  20764.0  6.700690  15.583909

In [41]:
# 고령자비율, 외국인비율이 높은 구는 어디인가?
# 고령자비율, 외국인비율이 낮은 구는 어디인가?
pop_seoul.sort_values(by='고령자비율', ascending=False).head()

      구별       인구수       한국인      외국인      고령자     외국인비율      고령자비율
9    강북구  330192.0  326686.0   3506.0  54813.0  1.061806  16.600342
1    종로구  162820.0  153589.0   9231.0  25425.0  5.669451  15.615404
2     중구  133240.0  124312.0   8928.0  20764.0  6.700690  15.583909
3    용산구  244203.0  229456.0  14747.0  36231.0  6.038828  14.836427
13  서대문구  327163.0  314982.0  12181.0  48161.0  3.723221  14.720797

In [42]:
pop_seoul.sort_values(by='고령자비율', ascending=False).tail()

     구별       인구수       한국인      외국인      고령자     외국인비율      고령자비율
22  서초구  450310.0  445994.0   4316.0  51733.0  0.958451  11.488308
5   광진구  372164.0  357211.0  14953.0  42214.0  4.017852  11.342849
23  강남구  570500.0  565550.0   4950.0  63167.0  0.867660  11.072217
15  양천구  479978.0  475949.0   4029.0  52975.0  0.839413  11.036964
24  송파구  667483.0  660584.0   6899.0  72506.0  1.033584  10.862599

In [43]:
pop_seoul.sort_values(by='외국인비율', ascending=False).head()

      구별       인구수       한국인      외국인      고령자     외국인비율      고령자비율
19  영등포구  402985.0  368072.0  34913.0  52413.0  8.663598  13.006191
18   금천구  255082.0  236353.0  18729.0  32970.0  7.342345  12.925255
17   구로구  447874.0  416487.0  31387.0  56833.0  7.007998  12.689506
2     중구  133240.0  124312.0   8928.0  20764.0  6.700690  15.583909
3    용산구  244203.0  229456.0  14747.0  36231.0  6.038828  14.836427

In [44]:
pop_seoul.sort_values(by='외국인비율', ascending=False).tail()

     구별       인구수       한국인     외국인      고령자     외국인비율      고령자비율
12  은평구  494388.0  489943.0  4445.0  72334.0  0.899091  14.631019
23  강남구  570500.0  565550.0  4950.0  63167.0  0.867660  11.072217
15  양천구  479978.0  475949.0  4029.0  52975.0  0.839413  11.036964
11  노원구  569384.0  565565.0  3819.0  71941.0  0.670725  12.634883
10  도봉구  348646.0  346629.0  2017.0  51312.0  0.578524  14.717507

In [45]:
cctv_seoul.head()

    구별    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613

In [46]:
#CCTV최근 증가률이 높은 곳/낮은 곳
cctv_seoul['최근증가율'] = (  cctv_seoul['2014년'] +
                                            cctv_seoul['2015년'] +
                                            cctv_seoul['2016년']
                                          ) / cctv_seoul['2013년도 이전'] * 100
cctv_seoul.head()

    구별    소계  2013년도 이전  2014년  2015년  2016년       최근증가율
0  강남구  2780       1292    430    584    932  150.619195
1  강동구   773        379     99    155    377  166.490765
2  강북구   748        369    120    138    204  125.203252
3  강서구   884        388    258    184     81  134.793814
4  관악구  1496        846    260    390    613  149.290780

In [47]:
cctv_seoul.sort_values(by='최근증가율', ascending=False).head()

     구별    소계  2013년도 이전  2014년  2015년  2016년       최근증가율
22  종로구  1002        464    314    211    630  248.922414
9   도봉구   485        238    159     42    386  246.638655
12  마포구   574        314    118    169    379  212.101911
8   노원구  1265        542     57    451    516  188.929889
1   강동구   773        379     99    155    377  166.490765

In [48]:
# sql문의 inner join과 동일한 이름의 컬럼이 있어야함. + 값의 도메인이 동일해야함.)
data_result = pd.merge(cctv_seoul, pop_seoul, on = '구별')
data_result.head()

,구별,소계,2013년도 이전,2014년,2015년,2016년,최근증가율,인구수,한국인,외국인,고령자,외국인비율,고령자비율
0,강남구,2780,1292,430,584,932,150.619195,570500.0,565550.0,4950.0,63167.0,0.867660,11.072217
1,강동구,773,379,99,155,377,166.490765,453233.0,449019.0,4214.0,54622.0,0.929765,12.051638
2,강북구,748,369,120,138,204,125.203252,330192.0,326686.0,3506.0,54813.0,1.061806,16.600342
3,강서구,884,388,258,184,81,134.793814,603772.0,597248.0,6524.0,72548.0,1.080540,12.015794
4,관악구,1496,846,260,390,613,149.290780,525515.0,507203.0,18312.0,68082.0,3.484582,12.955291

In [49]:
data_result.to_csv('cctv+pop+data_result.csv', encoding='UTF-8')

In [50]:
data_result.drop(columns=['2013년도 이전', '2014년', '2015년', '2016년'],
                            inplace=True
                )
data_result.head()

,구별,소계,최근증가율,인구수,한국인,외국인,고령자,외국인비율,고령자비율
0,강남구,2780,150.619195,570500.0,565550.0,4950.0,63167.0,0.867660,11.072217
1,강동구,773,166.490765,453233.0,449019.0,4214.0,54622.0,0.929765,12.051638
2,강북구,748,125.203252,330192.0,326686.0,3506.0,54813.0,1.061806,16.600342
3,강서구,884,134.793814,603772.0,597248.0,6524.0,72548.0,1.080540,12.015794
4,관악구,1496,149.290780,525515.0,507203.0,18312.0,68082.0,3.484582,12.955291

In [52]:
crime_seoul = pd.read_csv('../csv-data/crime_seoul_3.csv', encoding='euc-kr')
crime_seoul

      구별  살인 발생  강도 발생  강간 발생  절도 발생  폭력 발생
0     중구      2      3    105   1395   1355
1    종로구      3      6    115   1070   1278
2     중구      1      6     65   1153    869
3   서대문구      2      5    154   1812   2056
4    종로구      3      5     96   1114   1015
5    용산구      5     14    194   1557   2050
6    성북구      2      2     86    953   1194
7   동대문구      5     13    173   1981   2548
8    마포구      8     14    294   2555   2983
9   영등포구     14     22    295   2964   3572
10   성동구      4      9    126   1607   1612
11   동작구      5      9    285   1865   1910
12   광진구      4     14    240   3026   2625
13   은평구      2      2     70    819   1192
14   강북구      7     14    153   1434   2649
15   금천구      3      6    151   1567   2054
16   중랑구     13     11    187   2135   2847
17   강남구      3     15    300   2411   2465
18   관악구      9     12    320   2706   3298
19   강서구      7     13    262   2096   3207
20   강동구      4      6    156   2366   2712
21   성북구      3      3     64    832   1015
22   구로구      8     15    281   2335   3007
23   서초구      7      8    334   1982   1852
24   양천구      3      6    120   1890   2509
25   송파구     11     13    220   3239   3295
26   노원구     10      7    197   2193   2723
27   서초구      1      1     59    653    547
28   은평구      1      7     96   1095   1461
29   도봉구      3      9    102   1063   1487
30   강남구     10      6    149   1439   1819

In [54]:
# crime_seoul[조건][열][행]
# cs를 사용하면 원본을 그대로 유지한 채 다양한 테스트를 할 수 있음.
cs = crime_seoul.copy()
cs[cs['구별'] == '금천구']

     구별  살인 발생  강도 발생  강간 발생  절도 발생  폭력 발생
15  금천구      3      6    151   1567   2054

In [59]:
cs[cs['구별'] == '영등포구']

     구별  살인 발생  강도 발생  강간 발생  절도 발생  폭력 발생
9  영등포구     14     22    295   2964   3572

In [68]:
cs['살인 발생'].mean() #5

np.float64(5.258064516129032)

In [69]:
cs['살인 발생'].max()

14

In [70]:
cs['살인 발생'].idxmax()

9

In [71]:
cs['살인 발생'].min()

1

In [72]:
cs['살인 발생'].idxmin()

2

In [74]:
cs.iloc[9]

구별       영등포구
살인 발생      14
강도 발생      22
강간 발생     295
절도 발생    2964
폭력 발생    3572
Name: 9, dtype: object

In [73]:
cs.iloc[2]

구별         중구
살인 발생       1
강도 발생       6
강간 발생      65
절도 발생    1153
폭력 발생     869
Name: 2, dtype: object

In [75]:
cs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   구별      31 non-null     object
 1   살인 발생   31 non-null     int64
 2   강도 발생   31 non-null     int64
 3   강간 발생   31 non-null     int64
 4   절도 발생   31 non-null     int64
 5   폭력 발생   31 non-null     int64
dtypes: int64(5), object(1)
memory usage: 1.6+ KB

In [76]:
cs.describe()

           살인 발생      강도 발생       강간 발생        절도 발생        폭력 발생
count  31.000000  31.000000   31.000000    31.000000    31.000000
mean    5.258065   8.903226  175.774194  1784.096774  2103.419355
std     3.605253   4.935280   85.580259   699.948825   829.042330
min     1.000000   1.000000   59.000000   653.000000   547.000000
25%     3.000000   6.000000  103.500000  1133.500000  1408.000000
50%     4.000000   8.000000  154.000000  1812.000000  2054.000000
75%     7.500000  13.000000  251.000000  2264.000000  2717.500000
max    14.000000  22.000000  334.000000  3239.000000  3572.000000

In [77]:
data_result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   구별      25 non-null     object
 1   소계      25 non-null     int64
 2   최근증가율   25 non-null     float64
 3   인구수     25 non-null     float64
 4   한국인     25 non-null     float64
 5   외국인     25 non-null     float64
 6   고령자     25 non-null     float64
 7   외국인비율   25 non-null     float64
 8   고령자비율   25 non-null     float64
dtypes: float64(7), int64(1), object(1)
memory usage: 1.9+ KB

In [80]:
cs['구별'].unique()

array(['중구', '종로구', '서대문구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구',
       '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구',
       '강동구', '구로구', '서초구', '양천구', '송파구', '노원구', '도봉구'], dtype=object)

In [81]:
len(cs['구별'].unique())

25

In [82]:
cs

      구별  살인 발생  강도 발생  강간 발생  절도 발생  폭력 발생
0     중구      2      3    105   1395   1355
1    종로구      3      6    115   1070   1278
2     중구      1      6     65   1153    869
3   서대문구      2      5    154   1812   2056
4    종로구      3      5     96   1114   1015
5    용산구      5     14    194   1557   2050
6    성북구      2      2     86    953   1194
7   동대문구      5     13    173   1981   2548
8    마포구      8     14    294   2555   2983
9   영등포구     14     22    295   2964   3572
10   성동구      4      9    126   1607   1612
11   동작구      5      9    285   1865   1910
12   광진구      4     14    240   3026   2625
13   은평구      2      2     70    819   1192
14   강북구      7     14    153   1434   2649
15   금천구      3      6    151   1567   2054
16   중랑구     13     11    187   2135   2847
17   강남구      3     15    300   2411   2465
18   관악구      9     12    320   2706   3298
19   강서구      7     13    262   2096   3207
20   강동구      4      6    156   2366   2712
21   성북구      3      3     64    832   1015
22   구로구      8     15    281   2335   3007
23   서초구      7      8    334   1982   1852
24   양천구      3      6    120   1890   2509
25   송파구     11     13    220   3239   3295
26   노원구     10      7    197   2193   2723
27   서초구      1      1     59    653    547
28   은평구      1      7     96   1095   1461
29   도봉구      3      9    102   1063   1487
30   강남구     10      6    149   1439   1819

In [83]:
cs2 = pd.pivot_table(cs, index='구별', aggfunc=np.sum)
cs2

C:\Users\pc\AppData\Local\Temp\ipykernel_6416\1755181457.py:1: FutureWarning: The provided callable <function sum at 0x000001FA2B5CECA0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  cs2 = pd.pivot_table(cs, index='구별', aggfunc=np.sum)

      강간 발생  강도 발생  살인 발생  절도 발생  폭력 발생
구별
강남구     449     21     13   3850   4284
강동구     156      6      4   2366   2712
강북구     153     14      7   1434   2649
강서구     262     13      7   2096   3207
관악구     320     12      9   2706   3298
광진구     240     14      4   3026   2625
구로구     281     15      8   2335   3007
금천구     151      6      3   1567   2054
노원구     197      7     10   2193   2723
도봉구     102      9      3   1063   1487
동대문구    173     13      5   1981   2548
동작구     285      9      5   1865   1910
마포구     294     14      8   2555   2983
서대문구    154      5      2   1812   2056
서초구     393      9      8   2635   2399
성동구     126      9      4   1607   1612
성북구     150      5      5   1785   2209
송파구     220     13     11   3239   3295
양천구     120      6      3   1890   2509
영등포구    295     22     14   2964   3572
용산구     194     14      5   1557   2050
은평구     166      9      3   1914   2653
종로구     211     11      6   2184   2293
중구      170      9      3   2548   2224
중랑구     187     11     13   2135   2847

In [84]:
type(cs2)

pandas.core.frame.DataFrame

In [85]:
cs2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 강남구 to 중랑구
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   강간 발생   25 non-null     int64
 1   강도 발생   25 non-null     int64
 2   살인 발생   25 non-null     int64
 3   절도 발생   25 non-null     int64
 4   폭력 발생   25 non-null     int64
dtypes: int64(5)
memory usage: 1.2+ KB

In [86]:
# 내장된 위치를 가지고 행을 검색하고 싶으면 iloc
# 인덱스로 설정된 컬럼의 값을 가지고 행을 검색하고 싶으면 loc

In [88]:
cs2.iloc[0]

강간 발생     449
강도 발생      21
살인 발생      13
절도 발생    3850
폭력 발생    4284
Name: 강남구, dtype: int64

In [89]:
cs2.loc['중랑구']

강간 발생     187
강도 발생      11
살인 발생      13
절도 발생    2135
폭력 발생    2847
Name: 중랑구, dtype: int64

In [90]:
cctv_pop_data_result = pd.read_csv('cctv+pop+data_result.csv', encoding='utf-8')
cctv_pop_data_result[:5]

,Unnamed: 0,구별,소계,2013년도 이전,2014년,2015년,2016년,최근증가율,인구수,한국인,외국인,고령자,외국인비율,고령자비율
0,0,강남구,2780,1292,430,584,932,150.619195,570500.0,565550.0,4950.0,63167.0,0.867660,11.072217
1,1,강동구,773,379,99,155,377,166.490765,453233.0,449019.0,4214.0,54622.0,0.929765,12.051638
2,2,강북구,748,369,120,138,204,125.203252,330192.0,326686.0,3506.0,54813.0,1.061806,16.600342
3,3,강서구,884,388,258,184,81,134.793814,603772.0,597248.0,6524.0,72548.0,1.080540,12.015794
4,4,관악구,1496,846,260,390,613,149.290780,525515.0,507203.0,18312.0,68082.0,3.484582,12.955291

In [91]:
del cctv_pop_data_result['Unnamed: 0'] # 컬럼 하나 지울때는 drop보다는 del이 더 편함.
# drop은 원래 비파괴(inplace=True해야 파괴)
# del은 파괴(원본 df에서 삭제됨)

In [92]:
cctv_pop_data_result.columns

Index(['구별', '소계', '2013년도 이전', '2014년', '2015년', '2016년', '최근증가율', '인구수',
       '한국인', '외국인', '고령자', '외국인비율', '고령자비율'],
      dtype='object')

In [93]:
cs2.index

Index(['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구',
       '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구',
       '용산구', '은평구', '종로구', '중구', '중랑구'],
      dtype='object', name='구별')

In [95]:
total_data_result3 = pd.merge(cctv_pop_data_result, cs2, on="구별")
total_data_result3.head()

,구별,소계,2013년도 이전,2014년,2015년,2016년,최근증가율,인구수,한국인,외국인,고령자,외국인비율,고령자비율,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생
0,강남구,2780,1292,430,584,932,150.619195,570500.0,565550.0,4950.0,63167.0,0.867660,11.072217,449,21,13,3850,4284
1,강동구,773,379,99,155,377,166.490765,453233.0,449019.0,4214.0,54622.0,0.929765,12.051638,156,6,4,2366,2712
2,강북구,748,369,120,138,204,125.203252,330192.0,326686.0,3506.0,54813.0,1.061806,16.600342,153,14,7,1434,2649
3,강서구,884,388,258,184,81,134.793814,603772.0,597248.0,6524.0,72548.0,1.080540,12.015794,262,13,7,2096,3207
4,관악구,1496,846,260,390,613,149.290780,525515.0,507203.0,18312.0,68082.0,3.484582,12.955291,320,12,9,2706,3298

In [97]:
total_data_result3.columns

Index(['구별', '소계', '2013년도 이전', '2014년', '2015년', '2016년', '최근증가율', '인구수',
       '한국인', '외국인', '고령자', '외국인비율', '고령자비율', '강간 발생', '강도 발생', '살인 발생',
       '절도 발생', '폭력 발생'],
      dtype='object')

In [98]:
# total_data_result3.drop([지우고 싶은 컬럼들], axis=1, inplace=True)
# total_data_result3.drop(columns = [지우고 싶은 컬럼들], inplace=True)
total_data_result3.drop(columns = ['2013년도 이전', '2014년', '2015년', '2016년'], inplace=True)
total_data_result3.head(1)

,구별,소계,최근증가율,인구수,한국인,외국인,고령자,외국인비율,고령자비율,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생
0,강남구,2780,150.619195,570500.0,565550.0,4950.0,63167.0,0.86766,11.072217,449,21,13,3850,4284

In [99]:
total_data_result3.to_csv('total_data_result3.csv', encoding='UTF-8')