In [ ]:
# map함수

In [1]:
# --> 컬럼의 모든 행에 동일한 처리를 하고 싶을 때 사용(apply함수와 동일)
# --> 동일한 처리는 함수정의해서 쓸수도 있고, 람다함수를 사용할 수도 있고!!

In [2]:
# map함수 처리결과는 map객체임. 다시 컬럼에 넣으려면 list()를 이용해서 list로 바꿔주어야함.

In [4]:
# list(map(처리할함수명, 처리대상/값목록)

In [5]:
list(map(int, ['3','4','5']))

[3, 4, 5]

In [19]:
items = [' 로지텍마우스 ', ' 앱솔키보드 ']

In [10]:
# 1. for문 사용

In [11]:
for i in range(len(items)): # range(2) --> [0, 1]
    items[i] = items[i].strip()
items

['로지텍마우스', '앱솔키보드']

In [8]:
# 2. map함수 사용(별도의 함수 정의해서 사용)
# list(map(처리할함수명, 처리대상/값목록)

In [14]:
def strip_all(x):
    return x.strip();

In [15]:
items = list(map(strip_all, items))
items

['로지텍마우스', '앱솔키보드']

In [9]:
# 3. 람다함수 사용
# lambda 입력파라미터 : 처리해서 리턴

In [20]:
items = list(map(lambda x : x.strip(), items))
items

['로지텍마우스', '앱솔키보드']

In [21]:
# filter()는 조건에 맞는 것만 특정한 처리를 하고자 하는 경우 사용

In [24]:
animals = ['cat','tiger','dog','bird','monkey']

In [22]:
# 1. for문 사용

In [25]:
result = []

In [26]:
for x in animals: # 결과를 새로운 리스트에 넣을 때는 index가 필요없음. 꺼내는 용도는 in이 편함.
    if len(x) <= 3:
        result.append(x) # 리스트로 추가하는 부분
result

['cat', 'dog']

In [23]:
# 2. filter사용(특정한 함수 정의 사용)
# list(filter(처리할 함수, 처리할 대상))
# filter, map함수는 리스트로 따로 만들어주는 코드를 임의로 넣지 않고 list()함수를 이용

In [27]:
def word_check(x) : 
    # map, list에 넣을 함수를 처리 내용만 씀.
    # 리스트로 묶는거 쓰지 않음.
    # 이 함수는 컬럼 값 하나당 처리할 내용을 씀.
    return len(x) <= 3

In [28]:
result2 = list(filter(word_check, animals))
result2

['cat', 'dog']

In [ ]:
# 3. filter사용(람다함수 사용)

In [30]:
result3 = list(filter(lambda x : len(x) <= 3, animals))
result3

['cat', 'dog']

In [31]:
# 처리할대상.apply(처리할함수)
# df의 컬럼(Series)에만 사용 가능!
# list의 각 값에 동일한 처리를 하고 싶은 경우 map()을 써야함.
animals.apply(word_check)

AttributeError: 'list' object has no attribute 'apply'

In [32]:
import pandas as pd
import numpy as np

In [43]:
df1 = pd.DataFrame({
    'name' : ['홍길동','김길동','홍순신','정길동','송사임'],
    'age' : [100, 200, 300, 400, 500]
})
df1

  name  age
0  홍길동  100
1  김길동  200
2  홍순신  300
3  정길동  400
4  송사임  500

In [44]:
# 파생변수 = list(map(함수, 처리할대상))
df1['age_result'] = list(map(lambda x : x + 1, df1['age']))
df1

  name  age  age_result
0  홍길동  100         101
1  김길동  200         201
2  홍순신  300         301
3  정길동  400         401
4  송사임  500         501

In [45]:
# 파생변수 = list(map(lambda x : 참일때 리턴값 if 조건 else 거짓일때 리턴값, 처리할대상))
df1['age_result2'] = list(map(lambda x : x + 2 if x >= 400 else x, df1['age']))
df1

  name  age  age_result  age_result2
0  홍길동  100         101          100
1  김길동  200         201          200
2  홍순신  300         301          300
3  정길동  400         401          402
4  송사임  500         501          502

In [46]:
# 처리할대상.apply(처리할함수) --> 결과는 list
df1['age_result3'] = df1['age'].apply(lambda x : x + 3 if x >=400 else x)
df1

  name  age  age_result  age_result2  age_result3
0  홍길동  100         101          100          100
1  김길동  200         201          200          200
2  홍순신  300         301          300          300
3  정길동  400         401          402          403
4  송사임  500         501          502          503

In [47]:
df1['age_result4'] = df1['age'].map(lambda x : x + 4 if x >=400 else x)
df1

  name  age  age_result  age_result2  age_result3  age_result4
0  홍길동  100         101          100          100          100
1  김길동  200         201          200          200          200
2  홍순신  300         301          300          300          300
3  정길동  400         401          402          403          404
4  송사임  500         501          502          503          504

In [48]:
df2 = pd.DataFrame({
    'name' : ['홍길동','김길동','홍순신','정길동','송사임'],
    'age' : [100, 200, 300, 400, 500]
})
df2

  name  age
0  홍길동  100
1  김길동  200
2  홍순신  300
3  정길동  400
4  송사임  500

In [49]:
# 1. map함수 이용
# 함수 정의 map1(x) --> age에서 1을 빼서 리턴
# df2에서 age변수의 값을 꺼내 1을 빼준 후 파생변수 age_1에 저장후 df2 출력

In [53]:
def map1(x):
    return x - 1

In [58]:
df2['age_2'] = list(map(lambda x : x - 1, df2['age']))
df2

  name  age  age_1  age_2
0  홍길동  100     99     99
1  김길동  200    199    199
2  홍순신  300    299    299
3  정길동  400    399    399
4  송사임  500    499    499

In [50]:
# 2. map함수 이용
# 위 문제를 람다함수로 변경
# df2에서 age변수의 값을 꺼내 1을 빼준 후 파생변수 age_2에 저장후 df2 출력

In [55]:
df2['age_1'] = list(map(map1, df2['age']))
df2

  name  age  age_1
0  홍길동  100     99
1  김길동  200    199
2  홍순신  300    299
3  정길동  400    399
4  송사임  500    499

In [51]:
# 3. apply함수 이용 - 람다함수 이용
# df2에서 age변수의 값을 꺼내 1을 빼준 후 파생변수 age_3에 저장후 df2출력

In [59]:
df2['age_3'] = df2['age'].apply(map1)
df2

  name  age  age_1  age_2  age_3
0  홍길동  100     99     99     99
1  김길동  200    199    199    199
2  홍순신  300    299    299    299
3  정길동  400    399    399    399
4  송사임  500    499    499    499

In [52]:
# 4. apply함수 이용 - 일반함수 또는 람다함수 이용
# df2에서 name변수의 값에 "님"을 붙인 후 파생변수 name2에 저장후 df2출력

In [61]:
df2['name2'] = df2['name'].apply(lambda x : x + '님')
df2

  name  age  age_1  age_2  age_3 name2
0  홍길동  100     99     99     99  홍길동님
1  김길동  200    199    199    199  김길동님
2  홍순신  300    299    299    299  홍순신님
3  정길동  400    399    399    399  정길동님
4  송사임  500    499    499    499  송사임님