In [85]:
import pandas as pd
import numpy as np

In [86]:
df = pd.read_csv('../csv-data/titanic_train.csv')
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,body,home.dest
0,2,1,"Mellinger, Miss. Madeleine Violet",female,13.0,0,1,250644,19.5000,NaN,S,NaN,"England / Bennington, VT"
1,2,1,"Wells, Miss. Joan",female,4.0,1,1,29103,23.0000,NaN,S,NaN,"Cornwall / Akron, OH"
2,2,1,"Duran y More, Miss. Florentina",female,30.0,1,0,SC/PARIS 2148,13.8583,NaN,C,NaN,"Barcelona, Spain / Havana, Cuba"
3,3,0,"Scanlan, Mr. James",male,NaN,0,0,36209,7.7250,NaN,Q,NaN,NaN
4,3,1,"Bradley, Miss. Bridget Delia",female,22.0,0,0,334914,7.7250,NaN,Q,NaN,"Kingwilliamstown, Co Cork, Ireland Glens Falls..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,3,0,"Davies, Mr. Joseph",male,17.0,2,0,A/4 48873,8.0500,NaN,S,NaN,"West Bromwich, England Pontiac, MI"
894,3,0,"Lockyer, Mr. Edward",male,NaN,0,0,1222,7.8792,NaN,S,153.0,NaN
895,1,0,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,NaN,"Winnipeg, MB"
896,3,1,"Dorking, Mr. Edward Arthur",male,19.0,0,0,A/5. 10482,8.0500,NaN,S,NaN,"England Oglesby, IL"
897,1,1,"Clark, Mrs. Walter Miller (Virginia McDowell)",female,26.0,1,0,13508,136.7792,C89,C,NaN,"Los Angeles, CA"

In [87]:
df.info() # 전체 테이블에 대한 정보(컬럼이름, 데이터타입, null유무)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     898 non-null    int64
 1   survived   898 non-null    int64
 2   name       898 non-null    object
 3   sex        898 non-null    object
 4   age        728 non-null    float64
 5   sibsp      898 non-null    int64
 6   parch      898 non-null    int64
 7   ticket     898 non-null    object
 8   fare       898 non-null    float64
 9   cabin      211 non-null    object
 10  embarked   896 non-null    object
 11  body       84 non-null     float64
 12  home.dest  516 non-null    object
dtypes: float64(3), int64(4), object(6)
memory usage: 91.3+ KB

In [88]:
df.describe() # 숫자 컬럼들만 여러 정보들 보여줌.

,pclass,survived,age,sibsp,parch,fare,body
count,898.000000,898.000000,728.000000,898.000000,898.000000,898.000000,84.000000
mean,2.291759,0.381960,30.196882,0.535635,0.374165,32.509864,156.678571
std,0.843071,0.486138,13.919413,1.134913,0.842225,47.292940,98.227565
min,1.000000,0.000000,0.750000,0.000000,0.000000,0.000000,1.000000
25%,1.000000,0.000000,21.000000,0.000000,0.000000,7.895800,67.750000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,147.500000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,31.359375,246.000000
max,3.000000,1.000000,74.000000,8.000000,9.000000,512.329200,328.000000

In [89]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'body', 'home.dest'],
      dtype='object')

In [77]:
# 컬럼의 값을 하나씩 거내서 처리할 함수
# 컬럼의 값이 3개인 경우 이 함수는 3번 호출됨.
def pclass_convert(pclass):
    if pclass == 1:
        return "low"
    elif 2 <= pclass <= 3: # 2 <= pclass and pclass <= 3 / 파이썬에서만 유일한 문법
        return "middle"
    else:
        return "high"

In [78]:
# df['pclass'] = df['pclass'].apply(적용할 함수)
df['pclass'] = df['pclass'].apply(pclass_convert) # apply의 list(Series)
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,body,home.dest
0,middle,1,"Mellinger, Miss. Madeleine Violet",female,13.0,0,1,250644,19.5000,NaN,S,NaN,"England / Bennington, VT"
1,middle,1,"Wells, Miss. Joan",female,4.0,1,1,29103,23.0000,NaN,S,NaN,"Cornwall / Akron, OH"
2,middle,1,"Duran y More, Miss. Florentina",female,30.0,1,0,SC/PARIS 2148,13.8583,NaN,C,NaN,"Barcelona, Spain / Havana, Cuba"
3,middle,0,"Scanlan, Mr. James",male,NaN,0,0,36209,7.7250,NaN,Q,NaN,NaN
4,middle,1,"Bradley, Miss. Bridget Delia",female,22.0,0,0,334914,7.7250,NaN,Q,NaN,"Kingwilliamstown, Co Cork, Ireland Glens Falls..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,middle,0,"Davies, Mr. Joseph",male,17.0,2,0,A/4 48873,8.0500,NaN,S,NaN,"West Bromwich, England Pontiac, MI"
894,middle,0,"Lockyer, Mr. Edward",male,NaN,0,0,1222,7.8792,NaN,S,153.0,NaN
895,low,0,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,NaN,"Winnipeg, MB"
896,middle,1,"Dorking, Mr. Edward Arthur",male,19.0,0,0,A/5. 10482,8.0500,NaN,S,NaN,"England Oglesby, IL"
897,low,1,"Clark, Mrs. Walter Miller (Virginia McDowell)",female,26.0,1,0,13508,136.7792,C89,C,NaN,"Los Angeles, CA"

In [79]:
df['pclass'].value_counts()

pclass
middle    672
low       226
Name: count, dtype: int64

In [90]:
lam = lambda pclass : "low" if pclass == 1 else("middle" if 2 <= pclass <= 3 else "high")
df['pclass'] = df['pclass'].apply(lam)
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,body,home.dest
0,middle,1,"Mellinger, Miss. Madeleine Violet",female,13.0,0,1,250644,19.5000,NaN,S,NaN,"England / Bennington, VT"
1,middle,1,"Wells, Miss. Joan",female,4.0,1,1,29103,23.0000,NaN,S,NaN,"Cornwall / Akron, OH"
2,middle,1,"Duran y More, Miss. Florentina",female,30.0,1,0,SC/PARIS 2148,13.8583,NaN,C,NaN,"Barcelona, Spain / Havana, Cuba"
3,middle,0,"Scanlan, Mr. James",male,NaN,0,0,36209,7.7250,NaN,Q,NaN,NaN
4,middle,1,"Bradley, Miss. Bridget Delia",female,22.0,0,0,334914,7.7250,NaN,Q,NaN,"Kingwilliamstown, Co Cork, Ireland Glens Falls..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,middle,0,"Davies, Mr. Joseph",male,17.0,2,0,A/4 48873,8.0500,NaN,S,NaN,"West Bromwich, England Pontiac, MI"
894,middle,0,"Lockyer, Mr. Edward",male,NaN,0,0,1222,7.8792,NaN,S,153.0,NaN
895,low,0,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,NaN,"Winnipeg, MB"
896,middle,1,"Dorking, Mr. Edward Arthur",male,19.0,0,0,A/5. 10482,8.0500,NaN,S,NaN,"England Oglesby, IL"
897,low,1,"Clark, Mrs. Walter Miller (Virginia McDowell)",female,26.0,1,0,13508,136.7792,C89,C,NaN,"Los Angeles, CA"

In [91]:
def str_count(x) : 
    if len(x) >= 15:
        return "long"
    else:
        return "short"

In [92]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'body', 'home.dest'],
      dtype='object')

In [93]:
df['name_result'] = df['name'].apply(str_count)
df['name_result']

0      long
1      long
2      long
3      long
4      long
       ...
893    long
894    long
895    long
896    long
897    long
Name: name_result, Length: 898, dtype: object

In [94]:
df['name_result'].value_counts()

name_result
long     892
short      6
Name: count, dtype: int64

In [95]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'body', 'home.dest', 'name_result'],
      dtype='object')

In [96]:
df['survived'] = df['survived'].apply(lambda x : "생존" if x == 1 else "사망")
df['survived']

0      생존
1      생존
2      생존
3      사망
4      생존
       ..
893    사망
894    사망
895    사망
896    생존
897    생존
Name: survived, Length: 898, dtype: object

In [97]:
df['survived'].value_counts()

survived
사망    555
생존    343
Name: count, dtype: int64

In [98]:
def ages(age):
    if age < 10:
        return "유아"
    elif 10 <= age < 20:
        return "10대"
    elif 20 <= age < 30:
        return "20대"
    elif 30 <= age < 40:
        return "30대"
    elif 40 <= age < 50:
        return "40대"
    elif 50 <= age < 60:
        return "50대"
    else:
        return "60대 이상"

In [99]:
df['age'] = df['age'].apply(ages)
df['age']

0         10대
1          유아
2         30대
3      60대 이상
4         20대
        ...
893       10대
894    60대 이상
895    60대 이상
896       10대
897       20대
Name: age, Length: 898, dtype: object

In [100]:
df['age'].value_counts()

age
20대       246
60대 이상    199
30대       171
10대        94
40대        93
유아         49
50대        46
Name: count, dtype: int64

In [109]:
result_count = df['age'].value_counts()
type(result_count)

pandas.core.series.Series

In [105]:
def name_gender(name) : 
    if 'Mr' in name or 'Dr' in name:
        return "남자"
    elif 'Miss' in name:
        return "여자"
    else:
        return "기타"

In [107]:
df['name_result2'] = df['name'].apply(name_gender)
df['name_result2']

0      여자
1      여자
2      여자
3      남자
4      여자
       ..
893    남자
894    남자
895    남자
896    남자
897    남자
Name: name_result2, Length: 898, dtype: object

In [108]:
df['name_result2'].value_counts()

name_result2
남자    667
여자    177
기타     54
Name: count, dtype: int64

In [101]:
# 포함하고 있는지 판단
'가' in '가나다'

True

In [102]:
'가' not in '가나다'

False

In [103]:
'Mr' in 'Mr 선샤인' # 'Mr' in name

True