In [ ]:
import warnings
warnings.filterwarnings(action='ignore')
import pandas as pd

In [ ]:
train_df = pd.read_csv('/content/ratings_train.txt', encoding='utf8', sep='\t')
train_df

              id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[150000 rows x 3 columns]

In [ ]:
train_df['label'].value_counts()

label
0    75173
1    74827
Name: count, dtype: int64

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        150000 non-null  int64
 1   document  149995 non-null  object
 2   label     150000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 3.4+ MB

In [ ]:
train_df = train_df[train_df['document'].notnull()]
train_df

              id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[149995 rows x 3 columns]

In [ ]:
import re #규칙을 가지고 필터링해주는 라이브러리.!!!

In [ ]:
train_df['document'] = train_df['document'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))

In [ ]:
train_df.head()

         id                                           document  label
0   9976970                                  아 더빙 진짜 짜증나네요 목소리      0
1   3819312                         흠포스터보고 초딩영화줄오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                          교도소 이야기구먼 솔직히 재미는 없다평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화스파이더맨에서 늙어보이기만 했던 커스틴 던...      1

In [ ]:
test_df = pd.read_csv('/content/ratings_test.txt', encoding='utf8', sep='\t')
test_df

            id                                           document  label
0      6270596                                                굳 ㅋ      1
1      9274899                               GDNTOPCLASSINTHECLUB      0
2      8544678             뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아      0
3      6825595                   지루하지는 않은데 완전 막장임... 돈주고 보기에는....      0
4      6723715  3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??      0
...        ...                                                ...    ...
49995  4608761          오랜만에 평점 로긴했네ㅋㅋ 킹왕짱 쌈뽕한 영화를 만났습니다 강렬하게 육쾌함      1
49996  5308387       의지 박약들이나 하는거다 탈영은 일단 주인공 김대희 닮았고 이등병 찐따 OOOO      0
49997  9072549                 그림도 좋고 완성도도 높았지만... 보는 내내 불안하게 만든다      0
49998  5802125     절대 봐서는 안 될 영화.. 재미도 없고 기분만 잡치고.. 한 세트장에서 다 해먹네      0
49999  6070594                                         마무리는 또 왜이래      0

[50000 rows x 3 columns]

In [ ]:
test_df['label'].value_counts()

label
1    25173
0    24827
Name: count, dtype: int64

In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        50000 non-null  int64
 1   document  49997 non-null  object
 2   label     50000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.1+ MB

In [ ]:
test_df = test_df[test_df['document'].notnull()]
test_df

            id                                           document  label
0      6270596                                                굳 ㅋ      1
1      9274899                               GDNTOPCLASSINTHECLUB      0
2      8544678             뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아      0
3      6825595                   지루하지는 않은데 완전 막장임... 돈주고 보기에는....      0
4      6723715  3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??      0
...        ...                                                ...    ...
49995  4608761          오랜만에 평점 로긴했네ㅋㅋ 킹왕짱 쌈뽕한 영화를 만났습니다 강렬하게 육쾌함      1
49996  5308387       의지 박약들이나 하는거다 탈영은 일단 주인공 김대희 닮았고 이등병 찐따 OOOO      0
49997  9072549                 그림도 좋고 완성도도 높았지만... 보는 내내 불안하게 만든다      0
49998  5802125     절대 봐서는 안 될 영화.. 재미도 없고 기분만 잡치고.. 한 세트장에서 다 해먹네      0
49999  6070594                                         마무리는 또 왜이래      0

[49997 rows x 3 columns]

In [ ]:
test_df['document'] = test_df['document'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))
test_df

            id                                    document  label
0      6270596                                         굳 ㅋ      1
1      9274899                                                  0
2      8544678            뭐야 이 평점들은 나쁘진 않지만 점 짜리는 더더욱 아니잖아      0
3      6825595                   지루하지는 않은데 완전 막장임 돈주고 보기에는      0
4      6723715   만 아니었어도 별 다섯 개 줬을텐데 왜 로 나와서 제 심기를 불편하게 하죠      0
...        ...                                         ...    ...
49995  4608761   오랜만에 평점 로긴했네ㅋㅋ 킹왕짱 쌈뽕한 영화를 만났습니다 강렬하게 육쾌함      1
49996  5308387    의지 박약들이나 하는거다 탈영은 일단 주인공 김대희 닮았고 이등병 찐따       0
49997  9072549             그림도 좋고 완성도도 높았지만 보는 내내 불안하게 만든다      0
49998  5802125  절대 봐서는 안 될 영화 재미도 없고 기분만 잡치고 한 세트장에서 다 해먹네      0
49999  6070594                                  마무리는 또 왜이래      0

[49997 rows x 3 columns]

In [ ]:
# !pip install konlpy

In [ ]:
from konlpy.tag import Okt

In [ ]:
okt = Okt()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer(tokenizer= okt.morphs , ngram_range=(1, 2), min_df = 3, max_df = 0.9)
tfidf
# max_df : 정수 또는 [0.0, 1.0] 사이의 실수. 디폴트 1
#  최대 몇개 문서에 걸쳐 포함된 단어까지 단어 꾸러미에 담아 사용할 것인지
# min_df : 정수 또는 [0.0, 1.0] 사이의 실수. 디폴트 1
#  최소 몇개 문서에 걸쳐 포함된 단어를 단어 꾸러미에 담아 사용할 것인지
## ngram-range(1,2): 한글자가 따로 나오거나, 두 글자가 같이 나오는 빈도수의 matrix

TfidfVectorizer(max_df=0.9, min_df=3, ngram_range=(1, 2),
                tokenizer=<bound method Okt.morphs of <konlpy.tag._okt.Okt object at 0x7a2b4da75760>>)

In [ ]:
tfidf.fit(train_df['document'])

TfidfVectorizer(max_df=0.9, min_df=3, ngram_range=(1, 2),
                tokenizer=<bound method Okt.morphs of <konlpy.tag._okt.Okt object at 0x7a2b4da75760>>)

In [ ]:
train_tfidf_df = tfidf.transform(train_df['document'])
train_tfidf_df

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2703859 stored elements and shape (149995, 115612)>

In [ ]:
# tfidf.inverse_transform(train_tfidf_df)

In [ ]:
train_tfidf_df[0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
# 테스트하기 위해서 테스트 데이터도 1)fit, transform 2) transform(*******)
# 테스트데이터를 tfidf vectorize할때는 train데이터로 fit한 후, transform시켜야 함.
test_tfidf_df = tfidf.transform(test_df['document'])
test_tfidf_df

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 871912 stored elements and shape (49997, 115612)>

In [ ]:
### 1. 로지스틱 회귀 객체 생성
### 2. 트레인 데이터로 학습
### 3. 테스트 데이터로 예측
### 4. 정확도를 구해보세요.!
### 5. 입력한 데이터로 예측!!!!
###     입력한 데이터 한글이외 제외시키고, transform한 후, 예측!!!!

In [ ]:
from sklearn.linear_model import LogisticRegression

SA_lr = LogisticRegression(random_state = 0)

In [ ]:
SA_lr.fit(train_tfidf_df, train_df['label'])

LogisticRegression(random_state=0)

In [ ]:
test_predict = SA_lr.predict(test_tfidf_df)

In [ ]:
from sklearn.metrics import accuracy_score

print('감성 분석 정확도 : ', round(accuracy_score(test_df['label'], test_predict), 3))

감성 분석 정확도 :  0.852

In [ ]:
#st = input('감성 분석할 문장입력 >> ')
st = "웃자 ^o^ 오늘은 좋은 날이 될 것 같은 예감100%! ^^*"

In [ ]:
st2 = re.sub(r'[^ ㄱ-ㅎ|가-힣]+', "", st)
st2

'웃자  오늘은 좋은 날이 될 것 같은 예감 '

In [ ]:
st_tfidf_df = tfidf.transform([st2])
st_tfidf_df

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 16 stored elements and shape (1, 115612)>

In [ ]:
st2_predict = SA_lr.predict(st_tfidf_df)

In [ ]:
st2_predict

array([1])

In [ ]:
st2_predict[0]

np.int64(1)

In [ ]:
if(st2_predict== 0):
    print(st2 , "->> 부정 감성")
else :
    print(st2 , "->> 긍정 감성")

웃자  오늘은 좋은 날이 될 것 같은 예감  ->> 긍정 감성

In [ ]:
st3 = "짱나! 진짜야"

In [ ]:
st4 = re.sub(r'[^ ㄱ-ㅎ|가-힣]+', "", st3)
st4

'짱나 진짜야'

In [ ]:
# 1) 입력 텍스트의 피처 벡터화
st4_tfidf = tfidf.transform([st4])

# 2) 최적 감성분석 모델에 적용하여 감성 분석 평가
st4_predict2 = SA_lr.predict(st4_tfidf)

In [ ]:
st4_predict2[0]

np.int64(0)

In [ ]:
if(st4_predict2== 0):
    print(st3 , "->> 부정 감성")
else :
    print(st3 , "->> 긍정 감성")

짱나! 진짜야 ->> 부정 감성